---
- name: main / Install required loadbalancer libraries
  yum:
    name: "{{ loadbalancer_packages }}"
    state: installed

- name: main / Template a file to /etc/haproxy/haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg 
    owner: root
    group: root
    mode: '0644'

- name: main / Start haproxy service
  systemd:
    name: haproxy
    enabled: yes
    state: started