---
- name: main / Install required network libraries
  yum:
    name: "{{ network_packages }}"
    state: installed

- name: main / Start NetworkManager
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

- name: main / Add internal ethernet connection
  nmcli:
    type: ethernet
    conn_name: "{{ internal_network.conn_name }}"
    ip4: "{{ internal_network.ipv4 }}"
    state: present

- name: main / Disable ipv6 and Set ip forwading
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/99-custom.conf
    sysctl_set: yes
    reload: yes
    state: present
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv4.ip_forward
