---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos:7
    command: /sbin/init
    privileged: True
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
